### PR TITLE
Fix #33: Move macros to a dedicated object.

### LINKED ISSUE #33: After upgrade to 1.1.0, scala-reflect is required as a dependency on JVM
We upgraded to `portable-scala-reflect` 1.1.0 in this PR: zio/zio#4619 . If `scala-reflect` would not be newly added as a dependency, the compilation failed with
```
[error] /home/ondra/Projects/zio/core-tests/jvm/src/test/scala/zio/system/SystemSpec.scala:8:22: object io is not a member of package reflect
[error] import scala.reflect.io.File
[error]                      ^
```
But the dependency is added only as `"org.scala-lang" % "scala-reflect" % scalaVersion.value % Test`.
That caused issues for users of ZIO who wanted to run tests via the ZIO's sbt runner:
```
java.lang.NoClassDefFoundError: scala/reflect/api/TypeCreator
    at zio.test.sbt.BaseTestTask.specInstance$lzycompute(BaseTestTask.scala:18)
```
That was solved by adding `scala-reflect` as a regular Compile dependency in this PR: zio/zio#4645

/cc @sjrd

### PR DESCRIPTION
**Pull request by sideeffffect**
#fixes https://github.com/portable-scala/portable-scala-reflect/issues/33

/cc @sjrd @neko-kai @keynmol @adamgfraser

### CODE REVIEW

**Comment by sideeffffect** [comment]
Ready to be reviewed and merged :tada:

File: jvm/src/main/scala/org/portablescala/reflect/Reflect.scala [hunk 1]
```diff
@@ -9,25 +9,65 @@ import java.lang.reflect._
...
-  private object MacroCompat {
-    object Scope1 {
-      object blackbox
+
+  // Macro definitions are enclosed in a dedicated `Macros` object,
+  // so that their metadata (the types involved etc.) don't pollute `Reflect`'s metadata.
+  // This enables using `Reflect`'s methods without `scala-reflect` JAR
+  // https://github.com/scala/bug/issues/8090
+  // https://github.com/xeno-by/sbt-example-paradise210/issues/1#issuecomment-20996354
+  object Macros {
```
Comment (sjrd) [inline jvm/src/main/scala/org/portablescala/reflect/Reflect.scala]: IIUC the linked issue (in particular the second one; the first one doesn't seem to say anything), even putting this is an `object` within `object Reflect` is likely to cause errors downstream. And if it doesn't, it would be by chance and would be pretty fragile.

IMO we should put this in a separate, top-level objects. Since it unfortunately has to be public, we should put it in `org.portablescala.reflect.internal`.

Comment (sjrd) [reply jvm/src/main/scala/org/portablescala/reflect/Reflect.scala]: Also, please use `/* */` comments for non-Scaladoc multi-line comments. See https://github.com/scala-js/scala-js/blob/master/CODINGSTYLE.md#non-scaladoc-comments

File: build.sbt [hunk 2]
```diff
@@ -33,6 +34,15 @@ lazy val `portable-scala-reflect` = crossProject(JSPlatform, JVMPlatform, Native
...
       organization.value %%% moduleName.value % previousVersion,
+    mimaBinaryIssueFilters ++= List(
+      ProblemFilters.exclude[DirectMissingMethodProblem]("org.portablescala.reflect.Reflect.lookupInstantiatableClass_impl"),
+      ProblemFilters.exclude[DirectMissingMethodProblem]("org.portablescala.reflect.Reflect.lookupLoadableModuleClass_impl"),
+      ProblemFilters.exclude[MissingClassProblem]("org.portablescala.reflect.Reflect$MacroCompat$"),
+      ProblemFilters.exclude[MissingClassProblem]("org.portablescala.reflect.Reflect$MacroCompat$Scope1$"),
+      ProblemFilters.exclude[MissingClassProblem]("org.portablescala.reflect.Reflect$MacroCompat$Scope1$blackbox$"),
+      ProblemFilters.exclude[MissingClassProblem]("org.portablescala.reflect.Reflect$MacroCompat$Scope2$"),
+      ProblemFilters.exclude[MissingClassProblem]("org.portablescala.reflect.Reflect$MacroCompat$Scope2$Inner$"),
+    ),
```
Comment (sjrd) [inline build.sbt]: We should add comments to tell why those exclusions are OK. Also, we can leverage wildcards:
```suggestion
    mimaBinaryIssueFilters ++= List(
      // Macro implementations, not an issue
      ProblemFilters.exclude[DirectMissingMethodProblem]("org.portablescala.reflect.Reflect.lookupInstantiatableClass_impl"),
      ProblemFilters.exclude[DirectMissingMethodProblem]("org.portablescala.reflect.Reflect.lookupLoadableModuleClass_impl"),
      // Private, not an issue
      ProblemFilters.exclude[MissingClassProblem]("org.portablescala.reflect.Reflect$MacroCompat$*"),
    ),
```

**Review by sjrd — CHANGES_REQUESTED** [review]
I have a few comments.

Also, I have migrated the master branch to GitHub Actions, so please rebase this PR on top of the latest master to get the latest CI.

File: build.sbt (hunk 2 above)
Comment (sideeffffect) [reply build.sbt]: done :heavy_check_mark:

File: jvm/src/main/scala/org/portablescala/reflect/Reflect.scala (hunk 1 above)
Comment (sideeffffect) [reply jvm/src/main/scala/org/portablescala/reflect/Reflect.scala]: I have actually tested it locally and it worked, but separate object sounds more robust :+1: 
done :heavy_check_mark:

**Comment by sideeffffect** [comment]
@sjrd the build is green :tada:

**Comment by sideeffffect** [comment]
@sjrd do you think you could merge this PR and make a release, please? :pray:

**Review by sjrd — CHANGES_REQUESTED** [review]
LGTM. Could you squash into a single commit with a clean commit message that starts with `Fix #33: `, e.g.,

    Fix #33: Move macros to a dedicated object.

**Comment by sideeffffect** [comment]
Of course! Squashed :+1:

**Review by sjrd — APPROVED** [review]

**Comment by sideeffffect** [comment]
Could somebody please also make a release containing this fix? :pray:
